### ISSUE TITLE
Fix points overflow/wrapping issue

### ISSUE THREAD

**Issue by howardwang15** [uclaacm/membership-portal-ui#75]
## Motivation
Our points system wraps around if the user has too many points on the portal

<img width="938" alt="Screen Shot 2019-05-08 at 6 19 11 PM" src="https://user-images.githubusercontent.com/8008938/57553905-c30df700-7324-11e9-9509-95d3ad424cad.png">

<img width="1277" alt="Screen Shot 2019-05-08 at 6 18 52 PM" src="https://user-images.githubusercontent.com/8008938/57553951-e89b0080-7324-11e9-803c-6374fd58e009.png">

Right now, users level up when they reach a certain number of points...this may need to be updated.

## Todo

- [x] Update components/Profile/profile.js to avoid underflowing when calculating number of points to reach the next level

- [x] Update components/Sidebar/pointsBar.js to fix the width of the points bar so it doesn't go over 100%

- [x] Find if a new level needs to be added to avoid the overflow/underflow

**Comment by saiguy3** [comment]
A bug originates in: utils.js/config.js

Seems like if a user has more than 800 points, they are simply set to Level 1, which is a bug. Shown through pictures below.

<img width="456" alt="image" src="https://user-images.githubusercontent.com/8547495/57802250-633f9380-770a-11e9-9a61-fd412a83e9ef.png">

<img width="403" alt="image" src="https://user-images.githubusercontent.com/8547495/57802260-6a66a180-770a-11e9-9fee-28b834955bad.png">

**Comment by saiguy3** [comment]
#76
